#!/bin/sh

DISTRO=`cat /etc/*-release | grep ^ID= | grep -Po '".*?"' | tr -d '"'`

cat <<EOF
This is a S2I nodejs-${NODEJS_VERSION} ${DISTRO} base image with yarn as builder:
To use it, install S2I: https://github.com/openshift/source-to-image

Sample invocation:

s2i build <MY_GIT_REPO> <IMAGE_NAME> nodejs-sample-app

You can then run the resulting image via:
podman run -p 8080:8080 nodejs-sample-app
EOF
